:stylesheet: asciidoc-classic.css

= Manifesto

https://twitter.com/infosec1000grau[@Infosec1000grau]

IMPORTANT: Esse manifesto visa conscientizar sobre e abolir qualquer evento abusivo de cibersegurança e afins em território nacional.

== Greve contra qualquer evento que:

- Fique em lugar bosta
- Fale sobre acessibilidade web
- Custe mais de 100 pila pra entrar
- Tenha coisa de LGPD, GRC e os caralho
- Hospede CISM. CISM nem entra no evento!
- Não faça vista grossa para drogas ilícitas
- Não publique os palestrantes antes do evento
- Use a grana com alguma coisa estúpida/non-sense
- Não tenha brinde. Tem que ter brinde. No mínimo camiseta
- Tenha retardado que compila pdf em formato de pptx no LinkedIn
- Tenha profissionais CISSP. Portadores de CISSP são barrados de palestrar
- Não tenha nenhum tipo de constrangimento público. Tem que ter leak nos banheiros
- Não tenha stand de engenharia social, mesmo se for um gordo que nem fala com mulher
- O participante use dicas da Alura. Olharemos feio pra quem já abriu uma IDE na vida
- Patrocinador não dê brinde. Todo stand de patrocinador tem que dar brinde!!! Porque sim!!!
- Não tenha medidas de inclusão: pelo menos 30% dos palestrantes precisam ter histórico criminal
- Não oferte ingressos free para algumas empresas, para sabermos quais são fácilmente corruptíveis
- Tenha meninas de RH no stand ao invés de contratar promoters em sua maioria GPs, para reduzir custos
- Não tenha barzinho free com Vodka, Whiskey e refri é obrigatório. Principalmente se tiver treta na frente
- Não tenha palestras de weaponizing de itens físicos de uso básico e comum (como transformar um garfo numa faca)
- Não possua no minimo 1 (um) retardado que faça lockpicking, sendo que nem sai da própria casa, nem para comprar pão
- Impeça o aliciamento em cima de profissionais, o qual tem de ser pesado, afinal o cibercrime também é autorizado a recrutar
- Tenha alguém que nunca programou. Para participar do evento, tem que programar no mínimo um fizzbuzz na linguagem preferida
- Não tenha divisão de patrocínios de vendors por platinum, gold, prata e bronze - pois Sec é apenas uma questão de ego afinal...
- Tenha vendors conhecidos por serem braço-curto: Vendors com chamados abertos por clientes pendentes a mais de 1 mês terão sua participação reduzida
- Tenha Hackaflag patrocinado por vendor. CTF com ferramenta de vendor com ataques de 1980 para participantes desprovidos intelectualmente não passarão
- Vendedor coach. Vendedor só pode entrar depois de fazer uma prova básica de conceitos cyber e ter 90% de acerto! Terninho está terminantemente proibido.
- Se rolar briga, ninguém poderá apartar - O evento é o momento de resolver desavenças entre profissionais da área. Quando a lógica não funciona, sempre tem o brute-force
- Stand de fabricante sem demo! Ir nos eventos e não ver os SEs dos fabricantes chorando de tanto falar a mesma coisa pra um monte de gente que não vai comprar nada é reconfortante
- Tenha speaker remoto. Evento foda tem que ter Speaker foda presencialmente! Pagar pra assistir o cara via Live do Zoom do lado de um monte de gente olhando para um telão com som bosta eu assisto em casa
- Tenha membros da Nova Era Cibermística. Membros e palestrantes precisam disponibilizar histórico de e-mail dos últimos 12 meses para comprovar que não utilizaram as palavras "coach", "agile", "scrum" ou "security champions"
- O participante já tenha sido corrompido por recrutadoras gostosas. Quem saiu de uma empresa como sênior pra ir para uma outra como pleno, porque caiu na lábia de que ali era a maior da Améric Latina e os cambáu, nao poderá entrar!